#!/bin/bash 
#Cadence VIP example for xrun in mode 2s
#Usage:
#	${CDN_VIP_ROOT}/bin/cdn_vip_setup_example -e ${DENALI}/ddvapi/sv/uvm/cdn_axi/examples/using_config_object/axi4 \
#		-cdn_vip_root ${CDN_VIP_ROOT} \
#		-sim xrun -mode 2s -method sv_uvm -uvmver ieee -cdn_vip_lib $CDN_VIP_LIB_PATH -cdnautotest -64 


#CDN_VIP_COMMON_SRC:: Environment variable pointing to Cadence VIP common sv sources
CDN_VIP_COMMON_SRC=${DENALI}/ddvapi/sv
export CDN_VIP_COMMON_SRC

# Variables pointing to vip "axi" source sub-dir
CDN_VIP_AXI_RELEASE=${CDN_VIP_ROOT}
export CDN_VIP_AXI_RELEASE
CDN_VIP_AXI=${CDN_VIP_AXI_RELEASE}
export CDN_VIP_AXI
CDN_VIP_AXI_SRC=${CDN_VIP_AXI}/tools.lnx86/denali_64bit/ddvapi/sv/uvm/cdn_axi
export CDN_VIP_AXI_SRC
CDN_VIP_AXI_EXAMPLES=${CDN_VIP_AXI_SRC}/examples
export CDN_VIP_AXI_EXAMPLES
CDN_VIP_AXI_TC_EXAMPLES=/work/AbdulWasey/VIP_CAT/vipcat_11.30.094-08_Dec_2023_08_15_05/tools.lnx86/denali_64bit/triplecheck/axiTc/example
export CDN_VIP_AXI_TC_EXAMPLES

#Example Bitmode (32/64) from command-line (disable global variables bypassing command-line)
unset INCA_64BIT; unset CDS_AUTO_64BIT
#Disable a few other global variables bypassing command-line
unset NCSIMOPTS; unset NCVLOGOPTS; unset NCELABOPTS; unset NCVERILOGOPTS; unset XMSIMOPTS; unset XMVLOGOPTS; unset XMELABOPTS; unset XMVERILOGOPTS
#Location of core VIP libraries:
CDN_VIP_LIB_PATH=/work/AbdulWasey/AXI_Compiled_xbar/VIP/vip_lib
#Location of UVM source:
CDN_VIP_UVMHOME=${CDS_INST_DIR}/tools/methodology/UVM/CDNS-IEEE/sv

#The environment may be set up by uncommenting the following line:
#. cdn_vip_env_xrun_sv_uvm_64.sh
#Note: cdn_vip_env_xrun_sv_uvm_64.sh is generated by the following command:
#	${CDN_VIP_ROOT}/bin/cdn_vip_setup_env -cdn_vip_root ${CDN_VIP_ROOT} \
#		-sim xrun -mode 2s -method sv_uvm -uvmver ieee -cdn_vip_lib $CDN_VIP_LIB_PATH -cdnautotest -64 \
#		-sim_root <Root of IES install>

#The environment is validated by the following script:
#This script is intended to be executed before any simulation (or compile/if compile is a separate step)
#It can be commented out once you have confirmed that the environment is valid.
#IMPORTANT:: The environment must be validated on each new VIP download, change in simulator version
${CDN_VIP_ROOT}/bin/cdn_vip_check_env -cdn_vip_root ${CDN_VIP_ROOT} \
	-sim xrun -mode 2s -method sv_uvm -uvmver ieee -cdn_vip_lib $CDN_VIP_LIB_PATH -cdnautotest -64 -vips "axi"
if [ "$?" == "1" ]; then
	 exit 1
fi

#Key comments on xrun in mode 2s VIP compile:
#(b) To modify this script for your source code, modifications must start after 
#        ${DENALI}/ddvapi/sv/uvm/Cdn_axi/cdnAxiUvmTop.sv
#    All compile options including this line are necessary for Cadence VIPs.

#Compile System Verilog source files
xrun -elaborate -64 -mess -coverage all -sv -define DENALI_SV_NC \
	-define DENALI_UVM -uvmhome CDNS-IEEE \
	-access +rw \
	-warn_multiple_driver \
	-loadvpi ${DENALI}/verilog/libcdnsv.so:cdnsvVIP:export \
	-incdir ${DENALI}/ddvapi/sv \
	${DENALI}/ddvapi/sv/denaliMem.sv \
	${DENALI}/ddvapi/sv/denaliCdn_axi.sv \
	-incdir ${DENALI}/ddvapi/sv/uvm/cdn_axi \
	${DENALI}/ddvapi/sv/uvm/cdn_axi/cdnAxiUvmTop.sv \
	-incdir /home/wasey-10x/4interfaces_xbar/AXI_Compiled_xbar_working \
	-f /home/wasey-10x/4interfaces_xbar/AXI_Compiled_xbar_working/flist.f \
	-top testbench \
	+define+UVM_NO_DEPRECATED \
	-incdir /home/wasey-10x/4interfaces_xbar/AXI_Compiled_xbar_working/Testbench \
	-incdir ${DENALI}/ddvapi/sv/uvm/cdn_axi/examples/using_config_object \
	${DENALI}/ddvapi/sv/hdl_interfaces/cdn_axi/cb_interfaces/cdnAxi4Interface.sv \
	/home/wasey-10x/4interfaces_xbar/AXI_Compiled_xbar_working/Testbench/axi4UvmUserTop.sv \
	/home/wasey-10x/4interfaces_xbar/AXI_Compiled_xbar_working/Testbench/axi4UvmUserTb.sv \
	
declare -a TEST_NAMES=("write_from_mst0_to_slv0_test"  "write_from_mst0_to_slv1_test" "write_from_mst1_to_slv0_test" "write_from_mst1_to_slv1_test" "write_from_mst0_to_slv0_slv1_test" "write_from_mst1_to_slv0_slv1_test" "decode_error_test" "write_from_mst1_to_slv0_and_from_mst0_to_slv1_test" "write_using_sameID_tag_test" "read_axi_test" "read_after_write_test" "wrap_burst_test" "modify_trans_test")
# "perChannalDelayTest" "UnalignedTransferTest")
for TEST_NAME in "${TEST_NAMES[@]}"; do
#Simulate
xrun -R -64 \
	 -coverage all -covoverwrite -covfile /home/wasey-10x/4interfaces_xbar/AXI_Compiled_xbar_working/cov/covfile.ccf -covtest $TEST_NAME -sv_lib /home/wasey-10x/4interfaces_xbar/AXI_Compiled_xbar_working/Testbench/libcdnvipcuvm.so +UVM_TESTNAME=$TEST_NAME 
done


